ARG NODE_VERSION=22.16.0

FROM node:${NODE_VERSION}-alpine AS builder

ENV NODE_ENV=production

WORKDIR /app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

USER node

COPY . .

EXPOSE 3000

CMD ["node", "src/main.jsx"]